name: ReadMe GitHub Action 🦉

on:
  push:
    branches:
      - main

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `openapi` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: openapi TakeHomeExercise-1.0.0.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID}}
